### PR TITLE
testing/firestore: initial conformance tests for watch

### PR DESCRIPTION
**Pull request by jba**
Add protos for tests of the Listen RPC (a.k.a. watch).

Add a few preliminary tests. More to come.

### CODE REVIEW

**Comment by jba** [comment]
@schmidt-sebastian

**Comment by jskeet** [comment]
Will let @schmidt-sebastian handle this - I don't think I'm in a good position to review any Watch tests yet. Happy to *implement* the tests in C# when my Watch implementation is further along though.

**Comment by jba** [comment]
It tests that the implementation uses update time, and not change in the data, to decided that a document was modified.

**Comment by jba** [comment]
@schmidt-sebastian Can I merge this?

**Comment by schmidt-sebastian** [comment]
> Can I merge this?

Yes, please go ahead.

**Pull request merged**
